### ISSUE TITLE
[Baekjoon] 20168: 골목 대장 호석 - 기능성

### ISSUE THREAD

**Issue by sonsy0929** [GeumBi-Hong/2022-Java-Algorithm-Study#22]
[골목 대장 호석 - 기능성](https://www.acmicpc.net/problem/20168)

N이 작아서 다양한 풀이가 존재할 것이라 생각을 했습니다. 이 문제를 풀기 전에 [골목 대장 호석 - 효율성 2](https://www.acmicpc.net/problem/20183)를 먼저 풀어서 기존에 풀었던 풀이가 아닌 다른 풀이로 접근을 했습니다.

- 그래프를 인접 행렬로 구현하여 백트래킹
```java
// 시간초과
import java.io.*;
import java.util.*;

public class Main {
    static final int INF = (int)1e9;
    static int N, M, C, start, end;
    static int answer = INF;
    static int[][] edges = new int[15][15];
    static boolean[][] used = new boolean[15][15];
    public static void f(int curr, int dist) {
        if (dist > C) return;
        if (curr == end && dist <= C) {
            int maxCost = 0;
            for (int i = 1; i <= N; i++) {
                for (int j = 1; j <= N; j++) {
                    if (edges[i][j] == 0 || !used[i][j]) continue;
                    maxCost = Math.max(maxCost, edges[i][j]);
                }
            }
            answer = Math.min(answer, maxCost);
            return;
        }
        for (int i = 1; i <= N; i++) {
            if (edges[curr][i] == 0 || used[curr][i]) continue;
            used[curr][i] = true;
            f(i, dist + edges[curr][i]);
            used[curr][i] = false;
        }
    }
    public static void main(String[] args) throws IOException {
        BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
        StringTokenizer st = new StringTokenizer(br.readLine());
        N = Integer.parseInt(st.nextToken());
        M = Integer.parseInt(st.nextToken());
        start = Integer.parseInt(st.nextToken());
        end = Integer.parseInt(st.nextToken());
        C = Integer.parseInt(st.nextToken());
        for (int i = 1, u, v, w; i <= M; i++) {
            st = new StringTokenizer(br.readLine());
            u = Integer.parseInt(st.nextToken());
            v = Integer.parseInt(st.nextToken());
            w = Integer.parseInt(st.nextToken());
            edges[u][v] = edges[v][u] = w;
        }
        f(start, 0);
        System.out.println(answer != INF ? answer : -1);
    }
}
```
N이 작기 때문에 인접행렬로 구현해도 되지 않을까라는 생각을 가지고 풀었는데 시간초과가 발생하네요..
스터디 때 해당 주제로 같이 고민을 해주실 수 있을까요 ㅠㅠ.. 완전그래프가 형성될 때 시간초과가 발생하는 느낌이긴 한데.. c++로 구현해도 결국 똑같이 시간초과가 발생하더라구요 ㅎㅎ..

**Comment by GeumBi-Hong** [comment]
저도 인접행렬로 풀어봤습니다.  91% 구간에서 시간초과가 발생했습니다. 

아마 저와 같은 이유로 시간초과가 나시는거 같아서 적어봅니다.

먼저 시간초과가 나는 예시를 들어보겠습니다.

[예시]
10 45 1 10 1000000
1   2   1
1   3   1
1   4   1
1   5   1
1   6   1
1   7   1
1   8   1
1   9   1
1   10   1
2   3   1
2   4   1
2   5   1
2   6   1
2   7   1
2   8   1
2   9   1
2   10   1
3   4   1
3   5   1
3   6   1
3   7   1
3   8   1
3   9   1
3   10   1
4   5   1
4   6   1
4   7   1
4   8   1
4   9   1
4   10   1
5   6   1
5   7   1
5   8   1
5   9   1
5   10   1
6   7   1
6   8   1
6   9   1
6   10   1
7   8   1
7   9   1
7   10   1
8   9   1
8   10   1
9   10   1

정점의 수와 간선의 수가 최대라고 하였을때를 가정해보았습니다.
 상렬님의 코드를 가지고 이 예시를 실행해보면 3초가 훌쩍 넘고 결과가 나오지 않습니다.

왜 그런가 생각해보니 방문을 체크해주는 배열에서 문제가 발생하는것 같습니다.

[예제 입력1]을 기준으로 방문하는 정점을 찍어준다고 하였을때 1 -> 2 -> 3 ->1-> 4 -> 5 -> 3 으로 찍힐겁니다.

상렬님 코드로 정점을 찍어보면 그렇지 않습니다. 1- > 2 -> 1 -> 2 ..... 로  정점을 방문하고 있습니다. 

그 이유는 


   for (int i = 1; i <= N; i++) {
            if (edges[curr][i] == 0 || used[curr][i]) continue;
            used[curr][i] = true;
            f(i, dist + edges[curr][i]);
            used[curr][i] = false;
        }
    }


이 코드에서 정점이 1이였을 경우 used[curr =1] [i==2] =true;  가 되고
2로 이동하였을 경우   if (edges[curr][i] == 0 || used[curr][i]) continue;  에서
edges[curr=2][I==1] = 5 / used[curr=2][I=1] =false 이기 때문에 if문을 지나 f(1,~)가 라는 값으로 다시 실행 되기 때문입니다.
방문한 정점처리가 잘 안되있는걸 알 수 있습니다.  따라서 연산회수가 늘어나고 있다는걸 알 수 있습니다.

제 생각엔 이 부분에서 시간초과가 발생한게 아닌가 싶습니다 ! ㅎㅎ... 

제가 풀어본 코드도 같이 올려보겠습니다.

[코드]

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.StringTokenizer;
//골목대장 호석 - 기능성 (인접행렬)
public class Main {

    static int[][] map;
    static boolean[] visited;
    static int N,M,A,B,money;
    static int answer = Integer.MAX_VALUE;
    public static void main(String[] args) throws IOException {


        BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
        StringTokenizer st = new StringTokenizer(br.readLine()," ");



        N = Integer.parseInt(st.nextToken());
        M = Integer.parseInt(st.nextToken());
        A = Integer.parseInt(st.nextToken());
        B = Integer.parseInt(st.nextToken());
        money = Integer.parseInt(st.nextToken());


        map = new int[N+1][N+1];
        visited = new boolean[N+1];


        for(int i = 0 ; i <M;i++){
            st = new StringTokenizer(br.readLine(), " ");
            int start = Integer.parseInt(st.nextToken());
            int end = Integer.parseInt(st.nextToken());
            int cost = Integer.parseInt(st.nextToken());

            //양방향 관계
            map[start][end]=cost;
            map[end][start]=cost;

        }

        dfs(A,B,money,0);

        System.out.print(answer==Integer.MAX_VALUE? -1:answer);

    }


    public static void dfs (int start ,int end ,int money,int maxCost){

        if(start==end){
            answer=Math.min(answer,maxCost);
             //   System.out.println(start);
            return;
        }



        for(int i=1; i<=N;i++){

            //가중치가 없으면 넘어감 // //방문한 노드면 넘어감 //방문해야되는 노드가 방문했다면 넘어감
            if(map[start][i]==0 ||visited[start]||visited[i])continue;
            if(visited[start])continue;
            if(visited[i])continue;

            int cost = map[start][i];

            if(money<cost) continue; //돈이 없어도 넘어감

          //  System.out.println(start+" "+i);


            visited[start]=true;
            int max = Math.max(cost,maxCost);
            dfs(i,end,money-cost,max);
            visited[start]=false;

        }

    }
}

**Comment by sonsy0929** [comment]
덕분에 무엇때문에 시간초과인지 파악했습니다 ㅠㅠ 감사합니다!
